set(MBGL_CORE_FILES

        ############################################################### core-files.cmake ##

        # actor
        ${LIB_MBGL_SRC}/mbgl/algorithm/generate_clip_ids.hpp
        ${LIB_MBGL_SRC}/mbgl/algorithm/generate_clip_ids_impl.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/actor/scheduler.hpp
        ${LIB_MBGL_SRC}/mbgl/annotation/annotation_tile.hpp
        ${LIB_MBGL_SRC}/mbgl/annotation/annotation_manager.hpp
        ${LIB_MBGL_SRC}/mbgl/annotation/annotation_source.hpp


        ${LIB_MBGL_INCLUDE}/mbgl/actor/actor.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/actor/actor_ref.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/actor/aspiring_actor.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/actor/established_actor.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/actor/mailbox.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/actor/message.hpp
        ${LIB_MBGL_SRC}/mbgl/actor/mailbox.cpp
        ${LIB_MBGL_SRC}/mbgl/actor/scheduler.cpp

        # algorithm
        ${LIB_MBGL_SRC}/mbgl/algorithm/covered_by_children.hpp
        ${LIB_MBGL_SRC}/mbgl/algorithm/generate_clip_ids.cpp
        ${LIB_MBGL_SRC}/mbgl/algorithm/update_renderables.hpp
        ${LIB_MBGL_SRC}/mbgl/algorithm/update_tile_masks.hpp

        # annotation
        ${LIB_MBGL_INCLUDE}/mbgl/annotation/annotation.hpp
        ${LIB_MBGL_SRC}/mbgl/annotation/annotation_manager.cpp
        ${LIB_MBGL_SRC}/mbgl/annotation/annotation_source.cpp
        ${LIB_MBGL_SRC}/mbgl/annotation/annotation_tile.cpp
        ${LIB_MBGL_SRC}/mbgl/annotation/fill_annotation_impl.hpp
        ${LIB_MBGL_SRC}/mbgl/annotation/fill_annotation_impl.cpp
        ${LIB_MBGL_SRC}/mbgl/annotation/line_annotation_impl.cpp
        ${LIB_MBGL_SRC}/mbgl/annotation/line_annotation_impl.hpp
        ${LIB_MBGL_SRC}/mbgl/annotation/render_annotation_source.cpp
        ${LIB_MBGL_SRC}/mbgl/annotation/render_annotation_source.hpp
        ${LIB_MBGL_SRC}/mbgl/annotation/shape_annotation_impl.cpp
        ${LIB_MBGL_SRC}/mbgl/annotation/shape_annotation_impl.hpp
        ${LIB_MBGL_SRC}/mbgl/annotation/symbol_annotation_impl.cpp
        ${LIB_MBGL_SRC}/mbgl/annotation/symbol_annotation_impl.hpp

        # csscolorparser
        ${LIB_MBGL_SRC}/csscolorparser/csscolorparser.cpp
        ${LIB_MBGL_SRC}/csscolorparser/csscolorparser.hpp

        # geometry
        ${LIB_MBGL_SRC}/mbgl/geometry/anchor.hpp
        ${LIB_MBGL_SRC}/mbgl/geometry/debug_font_data.hpp
        ${LIB_MBGL_SRC}/mbgl/geometry/dem_data.cpp
        ${LIB_MBGL_SRC}/mbgl/geometry/dem_data.hpp
        ${LIB_MBGL_SRC}/mbgl/geometry/feature_index.cpp
        ${LIB_MBGL_SRC}/mbgl/geometry/feature_index.hpp
        ${LIB_MBGL_SRC}/mbgl/geometry/line_atlas.cpp
        ${LIB_MBGL_SRC}/mbgl/geometry/line_atlas.hpp

        # gfx
        ${LIB_MBGL_INCLUDE}/mbgl/gfx/backend_scope.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/gfx/renderable.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/gfx/renderer_backend.hpp
        ${LIB_MBGL_SRC}/mbgl/gfx/attribute.cpp
        ${LIB_MBGL_SRC}/mbgl/gfx/attribute.hpp
        ${LIB_MBGL_SRC}/mbgl/gfx/color_mode.hpp
        ${LIB_MBGL_SRC}/mbgl/gfx/command_encoder.hpp
        ${LIB_MBGL_SRC}/mbgl/gfx/context.hpp
        ${LIB_MBGL_SRC}/mbgl/gfx/context_impl.hpp
        ${LIB_MBGL_SRC}/mbgl/gfx/cull_face_mode.hpp
        ${LIB_MBGL_SRC}/mbgl/gfx/debug_group.hpp
        ${LIB_MBGL_SRC}/mbgl/gfx/depth_mode.hpp
        ${LIB_MBGL_SRC}/mbgl/gfx/draw_mode.hpp
        ${LIB_MBGL_SRC}/mbgl/gfx/draw_scope.hpp
        ${LIB_MBGL_SRC}/mbgl/gfx/index_buffer.hpp
        ${LIB_MBGL_SRC}/mbgl/gfx/index_vector.hpp
        ${LIB_MBGL_SRC}/mbgl/gfx/offscreen_texture.hpp
        ${LIB_MBGL_SRC}/mbgl/gfx/program.hpp
        ${LIB_MBGL_SRC}/mbgl/gfx/render_pass.hpp
        ${LIB_MBGL_SRC}/mbgl/gfx/renderbuffer.hpp
        ${LIB_MBGL_SRC}/mbgl/gfx/renderer_backend.cpp
        ${LIB_MBGL_SRC}/mbgl/gfx/stencil_mode.hpp
        ${LIB_MBGL_SRC}/mbgl/gfx/texture.hpp
        ${LIB_MBGL_SRC}/mbgl/gfx/types.hpp
        ${LIB_MBGL_SRC}/mbgl/gfx/uniform.hpp
        ${LIB_MBGL_SRC}/mbgl/gfx/vertex_buffer.hpp
        ${LIB_MBGL_SRC}/mbgl/gfx/vertex_vector.hpp

        # gl
        ${LIB_MBGL_INCLUDE}/mbgl/gl/renderable_resource.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/gl/renderer_backend.hpp
        ${LIB_MBGL_SRC}/mbgl/gl/attribute.cpp
        ${LIB_MBGL_SRC}/mbgl/gl/attribute.hpp
        ${LIB_MBGL_SRC}/mbgl/gl/binary_program.cpp
        ${LIB_MBGL_SRC}/mbgl/gl/binary_program.hpp
        ${LIB_MBGL_SRC}/mbgl/gl/command_encoder.cpp
        ${LIB_MBGL_SRC}/mbgl/gl/command_encoder.hpp
        ${LIB_MBGL_SRC}/mbgl/gl/context.cpp
        ${LIB_MBGL_SRC}/mbgl/gl/context.hpp
        ${LIB_MBGL_SRC}/mbgl/gl/debugging_extension.cpp
        ${LIB_MBGL_SRC}/mbgl/gl/debugging_extension.hpp
        ${LIB_MBGL_SRC}/mbgl/gl/defines.hpp
        ${LIB_MBGL_SRC}/mbgl/gl/draw_scope_resource.hpp
        ${LIB_MBGL_SRC}/mbgl/gl/enum.cpp
        ${LIB_MBGL_SRC}/mbgl/gl/enum.hpp
        ${LIB_MBGL_SRC}/mbgl/gl/extension.hpp
        ${LIB_MBGL_SRC}/mbgl/gl/features.hpp
        ${LIB_MBGL_SRC}/mbgl/gl/framebuffer.hpp
        ${LIB_MBGL_SRC}/mbgl/gl/index_buffer_resource.hpp
        ${LIB_MBGL_SRC}/mbgl/gl/object.cpp
        ${LIB_MBGL_SRC}/mbgl/gl/object.hpp
        ${LIB_MBGL_SRC}/mbgl/gl/offscreen_texture.cpp
        ${LIB_MBGL_SRC}/mbgl/gl/offscreen_texture.hpp
        ${LIB_MBGL_SRC}/mbgl/gl/program.hpp
        ${LIB_MBGL_SRC}/mbgl/gl/program_binary_extension.hpp
        ${LIB_MBGL_SRC}/mbgl/gl/render_pass.cpp
        ${LIB_MBGL_SRC}/mbgl/gl/render_pass.hpp
        ${LIB_MBGL_SRC}/mbgl/gl/renderbuffer_resource.hpp
        ${LIB_MBGL_SRC}/mbgl/gl/renderer_backend.cpp
        ${LIB_MBGL_SRC}/mbgl/gl/state.hpp
        ${LIB_MBGL_SRC}/mbgl/gl/texture.cpp
        ${LIB_MBGL_SRC}/mbgl/gl/texture.hpp
        ${LIB_MBGL_SRC}/mbgl/gl/texture_resource.hpp
        ${LIB_MBGL_SRC}/mbgl/gl/types.hpp
        ${LIB_MBGL_SRC}/mbgl/gl/uniform.cpp
        ${LIB_MBGL_SRC}/mbgl/gl/uniform.hpp
        ${LIB_MBGL_SRC}/mbgl/gl/value.cpp
        ${LIB_MBGL_SRC}/mbgl/gl/value.hpp
        ${LIB_MBGL_SRC}/mbgl/gl/vertex_array.cpp
        ${LIB_MBGL_SRC}/mbgl/gl/vertex_array.hpp
        ${LIB_MBGL_SRC}/mbgl/gl/vertex_array_extension.hpp
        ${LIB_MBGL_SRC}/mbgl/gl/vertex_buffer_resource.hpp

        # layermanager
        ${LIB_MBGL_INCLUDE}/mbgl/layermanager/background_layer_factory.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/layermanager/circle_layer_factory.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/layermanager/custom_layer_factory.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/layermanager/fill_extrusion_layer_factory.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/layermanager/fill_layer_factory.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/layermanager/heatmap_layer_factory.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/layermanager/hillshade_layer_factory.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/layermanager/layer_factory.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/layermanager/layer_manager.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/layermanager/line_layer_factory.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/layermanager/raster_layer_factory.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/layermanager/symbol_layer_factory.hpp
        ${LIB_MBGL_SRC}/mbgl/layermanager/background_layer_factory.cpp
        ${LIB_MBGL_SRC}/mbgl/layermanager/circle_layer_factory.cpp
        ${LIB_MBGL_SRC}/mbgl/layermanager/custom_layer_factory.cpp
        ${LIB_MBGL_SRC}/mbgl/layermanager/fill_extrusion_layer_factory.cpp
        ${LIB_MBGL_SRC}/mbgl/layermanager/fill_layer_factory.cpp
        ${LIB_MBGL_SRC}/mbgl/layermanager/heatmap_layer_factory.cpp
        ${LIB_MBGL_SRC}/mbgl/layermanager/hillshade_layer_factory.cpp
        ${LIB_MBGL_SRC}/mbgl/layermanager/layer_factory.cpp
        ${LIB_MBGL_SRC}/mbgl/layermanager/layer_manager.cpp
        ${LIB_MBGL_SRC}/mbgl/layermanager/line_layer_factory.cpp
        ${LIB_MBGL_SRC}/mbgl/layermanager/raster_layer_factory.cpp
        ${LIB_MBGL_SRC}/mbgl/layermanager/symbol_layer_factory.cpp

        # layout
        ${LIB_MBGL_SRC}/mbgl/layout/clip_lines.cpp
        ${LIB_MBGL_SRC}/mbgl/layout/clip_lines.hpp
        ${LIB_MBGL_SRC}/mbgl/layout/layout.hpp
        ${LIB_MBGL_SRC}/mbgl/layout/merge_lines.cpp
        ${LIB_MBGL_SRC}/mbgl/layout/merge_lines.hpp
        ${LIB_MBGL_SRC}/mbgl/layout/pattern_layout.hpp
        ${LIB_MBGL_SRC}/mbgl/layout/symbol_feature.hpp
        ${LIB_MBGL_SRC}/mbgl/layout/symbol_instance.cpp
        ${LIB_MBGL_SRC}/mbgl/layout/symbol_instance.hpp
        ${LIB_MBGL_SRC}/mbgl/layout/symbol_layout.cpp
        ${LIB_MBGL_SRC}/mbgl/layout/symbol_layout.hpp
        ${LIB_MBGL_SRC}/mbgl/layout/symbol_projection.cpp
        ${LIB_MBGL_SRC}/mbgl/layout/symbol_projection.hpp

        # map
        ${LIB_MBGL_INCLUDE}/mbgl/map/bound_options.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/map/camera.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/map/change.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/map/map.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/map/map_observer.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/map/map_options.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/map/mode.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/map/projection_mode.hpp
        ${LIB_MBGL_SRC}/mbgl/map/map.cpp
        ${LIB_MBGL_SRC}/mbgl/map/map_impl.cpp
        ${LIB_MBGL_SRC}/mbgl/map/map_impl.hpp
        ${LIB_MBGL_SRC}/mbgl/map/map_options.cpp
        ${LIB_MBGL_SRC}/mbgl/map/transform.cpp
        ${LIB_MBGL_SRC}/mbgl/map/transform.hpp
        ${LIB_MBGL_SRC}/mbgl/map/transform_state.cpp
        ${LIB_MBGL_SRC}/mbgl/map/transform_state.hpp
        ${LIB_MBGL_SRC}/mbgl/map/zoom_history.hpp

        # math
        ${LIB_MBGL_INCLUDE}/mbgl/math/clamp.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/math/log2.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/math/minmax.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/math/wrap.hpp
        ${LIB_MBGL_SRC}/mbgl/math/log2.cpp

        # parsedate
        ${LIB_MBGL_SRC}/parsedate/parsedate.cpp
        ${LIB_MBGL_SRC}/parsedate/parsedate.hpp

        # platform
        ${LIB_MBGL_INCLUDE}/mbgl/platform/gl_functions.hpp
        ${LIB_MBGL_SRC}/mbgl/platform/gl_functions.cpp

        # programs
        ${LIB_MBGL_SRC}/mbgl/programs/attributes.hpp
        ${LIB_MBGL_SRC}/mbgl/programs/background_pattern_program.hpp
        ${LIB_MBGL_SRC}/mbgl/programs/background_program.cpp
        ${LIB_MBGL_SRC}/mbgl/programs/background_program.hpp
        ${LIB_MBGL_SRC}/mbgl/programs/circle_program.cpp
        ${LIB_MBGL_SRC}/mbgl/programs/circle_program.hpp
        ${LIB_MBGL_SRC}/mbgl/programs/clipping_mask_program.cpp
        ${LIB_MBGL_SRC}/mbgl/programs/clipping_mask_program.hpp
        ${LIB_MBGL_SRC}/mbgl/programs/collision_box_program.cpp
        ${LIB_MBGL_SRC}/mbgl/programs/collision_box_program.hpp
        ${LIB_MBGL_SRC}/mbgl/programs/debug_program.cpp
        ${LIB_MBGL_SRC}/mbgl/programs/debug_program.hpp
        ${LIB_MBGL_SRC}/mbgl/programs/extrusion_texture_program.cpp
        ${LIB_MBGL_SRC}/mbgl/programs/extrusion_texture_program.hpp
        ${LIB_MBGL_SRC}/mbgl/programs/fill_extrusion_pattern_program.hpp
        ${LIB_MBGL_SRC}/mbgl/programs/fill_extrusion_program.cpp
        ${LIB_MBGL_SRC}/mbgl/programs/fill_extrusion_program.hpp
        ${LIB_MBGL_SRC}/mbgl/programs/fill_outline_pattern_program.hpp
        ${LIB_MBGL_SRC}/mbgl/programs/fill_outline_program.hpp
        ${LIB_MBGL_SRC}/mbgl/programs/fill_pattern_program.hpp
        ${LIB_MBGL_SRC}/mbgl/programs/fill_program.cpp
        ${LIB_MBGL_SRC}/mbgl/programs/fill_program.hpp
        ${LIB_MBGL_SRC}/mbgl/programs/heatmap_program.cpp
        ${LIB_MBGL_SRC}/mbgl/programs/heatmap_program.hpp
        ${LIB_MBGL_SRC}/mbgl/programs/heatmap_texture_program.cpp
        ${LIB_MBGL_SRC}/mbgl/programs/heatmap_texture_program.hpp
        ${LIB_MBGL_SRC}/mbgl/programs/hillshade_prepare_program.cpp
        ${LIB_MBGL_SRC}/mbgl/programs/hillshade_prepare_program.hpp
        ${LIB_MBGL_SRC}/mbgl/programs/hillshade_program.cpp
        ${LIB_MBGL_SRC}/mbgl/programs/hillshade_program.hpp
        ${LIB_MBGL_SRC}/mbgl/programs/line_gradient_program.hpp
        ${LIB_MBGL_SRC}/mbgl/programs/line_pattern_program.hpp
        ${LIB_MBGL_SRC}/mbgl/programs/line_program.cpp
        ${LIB_MBGL_SRC}/mbgl/programs/line_program.hpp
        ${LIB_MBGL_SRC}/mbgl/programs/line_sdf_program.hpp
        ${LIB_MBGL_SRC}/mbgl/programs/program.hpp
        ${LIB_MBGL_SRC}/mbgl/programs/program_parameters.cpp
        ${LIB_MBGL_SRC}/mbgl/programs/program_parameters.hpp
        ${LIB_MBGL_SRC}/mbgl/programs/programs.cpp
        ${LIB_MBGL_SRC}/mbgl/programs/programs.hpp
        ${LIB_MBGL_SRC}/mbgl/programs/raster_program.cpp
        ${LIB_MBGL_SRC}/mbgl/programs/raster_program.hpp
        ${LIB_MBGL_SRC}/mbgl/programs/segment.hpp
        ${LIB_MBGL_SRC}/mbgl/programs/symbol_icon_program.hpp
        ${LIB_MBGL_SRC}/mbgl/programs/symbol_program.cpp
        ${LIB_MBGL_SRC}/mbgl/programs/symbol_program.hpp
        ${LIB_MBGL_SRC}/mbgl/programs/symbol_sdf_icon_program.hpp
        ${LIB_MBGL_SRC}/mbgl/programs/symbol_sdf_text_program.hpp
        ${LIB_MBGL_SRC}/mbgl/programs/textures.hpp
        ${LIB_MBGL_SRC}/mbgl/programs/uniforms.hpp

        # programs/gl
        ${LIB_MBGL_SRC}/mbgl/programs/gl/background.cpp
        ${LIB_MBGL_SRC}/mbgl/programs/gl/background_pattern.cpp
        ${LIB_MBGL_SRC}/mbgl/programs/gl/circle.cpp
        ${LIB_MBGL_SRC}/mbgl/programs/gl/clipping_mask.cpp
        ${LIB_MBGL_SRC}/mbgl/programs/gl/collision_box.cpp
        ${LIB_MBGL_SRC}/mbgl/programs/gl/collision_circle.cpp
        ${LIB_MBGL_SRC}/mbgl/programs/gl/debug.cpp
        ${LIB_MBGL_SRC}/mbgl/programs/gl/extrusion_texture.cpp
        ${LIB_MBGL_SRC}/mbgl/programs/gl/fill.cpp
        ${LIB_MBGL_SRC}/mbgl/programs/gl/fill_extrusion.cpp
        ${LIB_MBGL_SRC}/mbgl/programs/gl/fill_extrusion_pattern.cpp
        ${LIB_MBGL_SRC}/mbgl/programs/gl/fill_outline.cpp
        ${LIB_MBGL_SRC}/mbgl/programs/gl/fill_outline_pattern.cpp
        ${LIB_MBGL_SRC}/mbgl/programs/gl/fill_pattern.cpp
        ${LIB_MBGL_SRC}/mbgl/programs/gl/heatmap.cpp
        ${LIB_MBGL_SRC}/mbgl/programs/gl/heatmap_texture.cpp
        ${LIB_MBGL_SRC}/mbgl/programs/gl/hillshade.cpp
        ${LIB_MBGL_SRC}/mbgl/programs/gl/hillshade_prepare.cpp
        ${LIB_MBGL_SRC}/mbgl/programs/gl/line.cpp
        ${LIB_MBGL_SRC}/mbgl/programs/gl/line_gradient.cpp
        ${LIB_MBGL_SRC}/mbgl/programs/gl/line_pattern.cpp
        ${LIB_MBGL_SRC}/mbgl/programs/gl/line_sdf.cpp
        ${LIB_MBGL_SRC}/mbgl/programs/gl/preludes.hpp
        ${LIB_MBGL_SRC}/mbgl/programs/gl/raster.cpp
        ${LIB_MBGL_SRC}/mbgl/programs/gl/shader_source.cpp
        ${LIB_MBGL_SRC}/mbgl/programs/gl/shader_source.hpp
        ${LIB_MBGL_SRC}/mbgl/programs/gl/shaders.cpp
        ${LIB_MBGL_SRC}/mbgl/programs/gl/shaders.hpp
        ${LIB_MBGL_SRC}/mbgl/programs/gl/symbol_icon.cpp
        ${LIB_MBGL_SRC}/mbgl/programs/gl/symbol_sdf_icon.cpp
        ${LIB_MBGL_SRC}/mbgl/programs/gl/symbol_sdf_text.cpp

        # renderer
        ${LIB_MBGL_INCLUDE}/mbgl/renderer/query.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/renderer/renderer.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/renderer/renderer_frontend.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/renderer/renderer_observer.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/renderer/renderer_state.hpp
        ${LIB_MBGL_SRC}/mbgl/renderer/backend_scope.cpp
        ${LIB_MBGL_SRC}/mbgl/renderer/bucket.hpp
        ${LIB_MBGL_SRC}/mbgl/renderer/bucket_parameters.cpp
        ${LIB_MBGL_SRC}/mbgl/renderer/bucket_parameters.hpp
        ${LIB_MBGL_SRC}/mbgl/renderer/cross_faded_property_evaluator.cpp
        ${LIB_MBGL_SRC}/mbgl/renderer/cross_faded_property_evaluator.hpp
        ${LIB_MBGL_SRC}/mbgl/renderer/data_driven_property_evaluator.hpp
        ${LIB_MBGL_SRC}/mbgl/renderer/group_by_layout.cpp
        ${LIB_MBGL_SRC}/mbgl/renderer/group_by_layout.hpp
        ${LIB_MBGL_SRC}/mbgl/renderer/image_atlas.cpp
        ${LIB_MBGL_SRC}/mbgl/renderer/image_atlas.hpp
        ${LIB_MBGL_SRC}/mbgl/renderer/image_manager.cpp
        ${LIB_MBGL_SRC}/mbgl/renderer/image_manager.hpp
        ${LIB_MBGL_SRC}/mbgl/renderer/paint_parameters.cpp
        ${LIB_MBGL_SRC}/mbgl/renderer/paint_parameters.hpp
        ${LIB_MBGL_SRC}/mbgl/renderer/paint_property_binder.hpp
        ${LIB_MBGL_SRC}/mbgl/renderer/paint_property_statistics.hpp
        ${LIB_MBGL_SRC}/mbgl/renderer/possibly_evaluated_property_value.hpp
        ${LIB_MBGL_SRC}/mbgl/renderer/property_evaluation_parameters.hpp
        ${LIB_MBGL_SRC}/mbgl/renderer/property_evaluator.hpp
        ${LIB_MBGL_SRC}/mbgl/renderer/render_layer.cpp
        ${LIB_MBGL_SRC}/mbgl/renderer/render_layer.hpp
        ${LIB_MBGL_SRC}/mbgl/renderer/render_light.cpp
        ${LIB_MBGL_SRC}/mbgl/renderer/render_light.hpp
        ${LIB_MBGL_SRC}/mbgl/renderer/render_pass.hpp
        ${LIB_MBGL_SRC}/mbgl/renderer/render_source.cpp
        ${LIB_MBGL_SRC}/mbgl/renderer/render_source.hpp
        ${LIB_MBGL_SRC}/mbgl/renderer/render_source_observer.hpp
        ${LIB_MBGL_SRC}/mbgl/renderer/render_static_data.cpp
        ${LIB_MBGL_SRC}/mbgl/renderer/render_static_data.hpp
        ${LIB_MBGL_SRC}/mbgl/renderer/render_tile.cpp
        ${LIB_MBGL_SRC}/mbgl/renderer/render_tile.hpp
        ${LIB_MBGL_SRC}/mbgl/renderer/renderer.cpp
        ${LIB_MBGL_SRC}/mbgl/renderer/renderer_impl.cpp
        ${LIB_MBGL_SRC}/mbgl/renderer/renderer_impl.hpp
        ${LIB_MBGL_SRC}/mbgl/renderer/renderer_state.cpp
        ${LIB_MBGL_SRC}/mbgl/renderer/style_diff.cpp
        ${LIB_MBGL_SRC}/mbgl/renderer/style_diff.hpp
        ${LIB_MBGL_SRC}/mbgl/renderer/tile_mask.hpp
        ${LIB_MBGL_SRC}/mbgl/renderer/tile_parameters.hpp
        ${LIB_MBGL_SRC}/mbgl/renderer/tile_pyramid.cpp
        ${LIB_MBGL_SRC}/mbgl/renderer/tile_pyramid.hpp
        ${LIB_MBGL_SRC}/mbgl/renderer/transition_parameters.hpp
        ${LIB_MBGL_SRC}/mbgl/renderer/update_parameters.hpp

        # renderer/buckets
        ${LIB_MBGL_SRC}/mbgl/renderer/buckets/circle_bucket.cpp
        ${LIB_MBGL_SRC}/mbgl/renderer/buckets/circle_bucket.hpp
        ${LIB_MBGL_SRC}/mbgl/renderer/buckets/debug_bucket.cpp
        ${LIB_MBGL_SRC}/mbgl/renderer/buckets/debug_bucket.hpp
        ${LIB_MBGL_SRC}/mbgl/renderer/buckets/fill_bucket.cpp
        ${LIB_MBGL_SRC}/mbgl/renderer/buckets/fill_bucket.hpp
        ${LIB_MBGL_SRC}/mbgl/renderer/buckets/fill_extrusion_bucket.cpp
        ${LIB_MBGL_SRC}/mbgl/renderer/buckets/fill_extrusion_bucket.hpp
        ${LIB_MBGL_SRC}/mbgl/renderer/buckets/heatmap_bucket.cpp
        ${LIB_MBGL_SRC}/mbgl/renderer/buckets/heatmap_bucket.hpp
        ${LIB_MBGL_SRC}/mbgl/renderer/buckets/hillshade_bucket.cpp
        ${LIB_MBGL_SRC}/mbgl/renderer/buckets/hillshade_bucket.hpp
        ${LIB_MBGL_SRC}/mbgl/renderer/buckets/line_bucket.cpp
        ${LIB_MBGL_SRC}/mbgl/renderer/buckets/line_bucket.hpp
        ${LIB_MBGL_SRC}/mbgl/renderer/buckets/raster_bucket.cpp
        ${LIB_MBGL_SRC}/mbgl/renderer/buckets/raster_bucket.hpp
        ${LIB_MBGL_SRC}/mbgl/renderer/buckets/symbol_bucket.cpp
        ${LIB_MBGL_SRC}/mbgl/renderer/buckets/symbol_bucket.hpp

        # renderer/layers
        ${LIB_MBGL_SRC}/mbgl/renderer/layers/render_background_layer.cpp
        ${LIB_MBGL_SRC}/mbgl/renderer/layers/render_background_layer.hpp
        ${LIB_MBGL_SRC}/mbgl/renderer/layers/render_circle_layer.cpp
        ${LIB_MBGL_SRC}/mbgl/renderer/layers/render_circle_layer.hpp
        ${LIB_MBGL_SRC}/mbgl/renderer/layers/render_custom_layer.cpp
        ${LIB_MBGL_SRC}/mbgl/renderer/layers/render_custom_layer.hpp
        ${LIB_MBGL_SRC}/mbgl/renderer/layers/render_fill_extrusion_layer.cpp
        ${LIB_MBGL_SRC}/mbgl/renderer/layers/render_fill_extrusion_layer.hpp
        ${LIB_MBGL_SRC}/mbgl/renderer/layers/render_fill_layer.cpp
        ${LIB_MBGL_SRC}/mbgl/renderer/layers/render_fill_layer.hpp
        ${LIB_MBGL_SRC}/mbgl/renderer/layers/render_heatmap_layer.cpp
        ${LIB_MBGL_SRC}/mbgl/renderer/layers/render_heatmap_layer.hpp
        ${LIB_MBGL_SRC}/mbgl/renderer/layers/render_hillshade_layer.cpp
        ${LIB_MBGL_SRC}/mbgl/renderer/layers/render_hillshade_layer.hpp
        ${LIB_MBGL_SRC}/mbgl/renderer/layers/render_layer_symbol_interface.hpp
        ${LIB_MBGL_SRC}/mbgl/renderer/layers/render_line_layer.cpp
        ${LIB_MBGL_SRC}/mbgl/renderer/layers/render_line_layer.hpp
        ${LIB_MBGL_SRC}/mbgl/renderer/layers/render_raster_layer.cpp
        ${LIB_MBGL_SRC}/mbgl/renderer/layers/render_raster_layer.hpp
        ${LIB_MBGL_SRC}/mbgl/renderer/layers/render_symbol_layer.cpp
        ${LIB_MBGL_SRC}/mbgl/renderer/layers/render_symbol_layer.hpp

        # renderer/sources
        ${LIB_MBGL_SRC}/mbgl/renderer/sources/render_custom_geometry_source.cpp
        ${LIB_MBGL_SRC}/mbgl/renderer/sources/render_custom_geometry_source.hpp
        ${LIB_MBGL_SRC}/mbgl/renderer/sources/render_geojson_source.cpp
        ${LIB_MBGL_SRC}/mbgl/renderer/sources/render_geojson_source.hpp
        ${LIB_MBGL_SRC}/mbgl/renderer/sources/render_image_source.cpp
        ${LIB_MBGL_SRC}/mbgl/renderer/sources/render_image_source.hpp
        ${LIB_MBGL_SRC}/mbgl/renderer/sources/render_raster_dem_source.cpp
        ${LIB_MBGL_SRC}/mbgl/renderer/sources/render_raster_dem_source.hpp
        ${LIB_MBGL_SRC}/mbgl/renderer/sources/render_raster_source.cpp
        ${LIB_MBGL_SRC}/mbgl/renderer/sources/render_raster_source.hpp
        ${LIB_MBGL_SRC}/mbgl/renderer/sources/render_vector_source.cpp
        ${LIB_MBGL_SRC}/mbgl/renderer/sources/render_vector_source.hpp

        # sprite
        ${LIB_MBGL_SRC}/mbgl/sprite/sprite_loader.cpp
        ${LIB_MBGL_SRC}/mbgl/sprite/sprite_loader.hpp
        ${LIB_MBGL_SRC}/mbgl/sprite/sprite_loader_observer.hpp
        ${LIB_MBGL_SRC}/mbgl/sprite/sprite_loader_worker.cpp
        ${LIB_MBGL_SRC}/mbgl/sprite/sprite_loader_worker.hpp
        ${LIB_MBGL_SRC}/mbgl/sprite/sprite_parser.cpp
        ${LIB_MBGL_SRC}/mbgl/sprite/sprite_parser.hpp

        # storage
        ${LIB_MBGL_INCLUDE}/mbgl/storage/default_file_source.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/storage/file_source.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/storage/network_status.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/storage/offline.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/storage/online_file_source.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/storage/resource.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/storage/resource_options.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/storage/resource_transform.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/storage/response.hpp
        ${LIB_MBGL_SRC}/mbgl/storage/asset_file_source.hpp
        ${LIB_MBGL_SRC}/mbgl/storage/file_source.cpp
        ${LIB_MBGL_SRC}/mbgl/storage/http_file_source.hpp
        ${LIB_MBGL_SRC}/mbgl/storage/local_file_source.hpp
        ${LIB_MBGL_SRC}/mbgl/storage/network_status.cpp
        ${LIB_MBGL_SRC}/mbgl/storage/resource.cpp
        ${LIB_MBGL_SRC}/mbgl/storage/resource_options.cpp
        ${LIB_MBGL_SRC}/mbgl/storage/resource_transform.cpp
        ${LIB_MBGL_SRC}/mbgl/storage/response.cpp

        # style
        ${LIB_MBGL_INCLUDE}/mbgl/style/color_ramp_property_value.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/style/conversion.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/style/conversion_impl.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/style/filter.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/style/image.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/style/layer.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/style/layer_properties.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/style/light.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/style/position.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/style/property_expression.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/style/property_value.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/style/source.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/style/style.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/style/transition_options.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/style/types.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/style/undefined.hpp
        ${LIB_MBGL_SRC}/mbgl/style/collection.hpp
        ${LIB_MBGL_SRC}/mbgl/style/custom_tile_loader.cpp
        ${LIB_MBGL_SRC}/mbgl/style/custom_tile_loader.hpp
        ${LIB_MBGL_SRC}/mbgl/style/filter.cpp
        ${LIB_MBGL_SRC}/mbgl/style/image.cpp
        ${LIB_MBGL_SRC}/mbgl/style/image_impl.cpp
        ${LIB_MBGL_SRC}/mbgl/style/image_impl.hpp
        ${LIB_MBGL_SRC}/mbgl/style/layer.cpp
        ${LIB_MBGL_SRC}/mbgl/style/layer_impl.cpp
        ${LIB_MBGL_SRC}/mbgl/style/layer_impl.hpp
        ${LIB_MBGL_SRC}/mbgl/style/layer_observer.hpp
        ${LIB_MBGL_SRC}/mbgl/style/layout_property.hpp
        ${LIB_MBGL_SRC}/mbgl/style/light.cpp
        ${LIB_MBGL_SRC}/mbgl/style/light_impl.cpp
        ${LIB_MBGL_SRC}/mbgl/style/light_impl.hpp
        ${LIB_MBGL_SRC}/mbgl/style/light_observer.hpp
        ${LIB_MBGL_SRC}/mbgl/style/observer.hpp
        ${LIB_MBGL_SRC}/mbgl/style/paint_property.hpp
        ${LIB_MBGL_SRC}/mbgl/style/parser.cpp
        ${LIB_MBGL_SRC}/mbgl/style/parser.hpp
        ${LIB_MBGL_SRC}/mbgl/style/properties.hpp
        ${LIB_MBGL_SRC}/mbgl/style/property_expression.cpp
        ${LIB_MBGL_SRC}/mbgl/style/rapidjson_conversion.hpp
        ${LIB_MBGL_SRC}/mbgl/style/source.cpp
        ${LIB_MBGL_SRC}/mbgl/style/source_impl.cpp
        ${LIB_MBGL_SRC}/mbgl/style/source_impl.hpp
        ${LIB_MBGL_SRC}/mbgl/style/source_observer.hpp
        ${LIB_MBGL_SRC}/mbgl/style/style.cpp
        ${LIB_MBGL_SRC}/mbgl/style/style_impl.cpp
        ${LIB_MBGL_SRC}/mbgl/style/style_impl.hpp
        ${LIB_MBGL_SRC}/mbgl/style/types.cpp

        # style/conversion
        ${LIB_MBGL_INCLUDE}/mbgl/style/conversion/color_ramp_property_value.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/style/conversion/constant.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/style/conversion/coordinate.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/style/conversion/custom_geometry_source_options.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/style/conversion/filter.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/style/conversion/function.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/style/conversion/geojson.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/style/conversion/geojson_options.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/style/conversion/get_json_type.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/style/conversion/layer.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/style/conversion/light.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/style/conversion/position.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/style/conversion/property_value.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/style/conversion/source.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/style/conversion/tileset.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/style/conversion/transition_options.hpp
        ${LIB_MBGL_SRC}/mbgl/style/conversion/color_ramp_property_value.cpp
        ${LIB_MBGL_SRC}/mbgl/style/conversion/constant.cpp
        ${LIB_MBGL_SRC}/mbgl/style/conversion/coordinate.cpp
        ${LIB_MBGL_SRC}/mbgl/style/conversion/custom_geometry_source_options.cpp
        ${LIB_MBGL_SRC}/mbgl/style/conversion/filter.cpp
        ${LIB_MBGL_SRC}/mbgl/style/conversion/function.cpp
        ${LIB_MBGL_SRC}/mbgl/style/conversion/geojson.cpp
        ${LIB_MBGL_SRC}/mbgl/style/conversion/geojson_options.cpp
        ${LIB_MBGL_SRC}/mbgl/style/conversion/get_json_type.cpp
        ${LIB_MBGL_SRC}/mbgl/style/conversion/json.hpp
        ${LIB_MBGL_SRC}/mbgl/style/conversion/layer.cpp
        ${LIB_MBGL_SRC}/mbgl/style/conversion/light.cpp
        ${LIB_MBGL_SRC}/mbgl/style/conversion/position.cpp
        ${LIB_MBGL_SRC}/mbgl/style/conversion/property_value.cpp
        ${LIB_MBGL_SRC}/mbgl/style/conversion/source.cpp
        ${LIB_MBGL_SRC}/mbgl/style/conversion/stringify.hpp
        ${LIB_MBGL_SRC}/mbgl/style/conversion/tileset.cpp
        ${LIB_MBGL_SRC}/mbgl/style/conversion/transition_options.cpp

        # style/expression
        ${LIB_MBGL_INCLUDE}/mbgl/style/expression/assertion.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/style/expression/at.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/style/expression/boolean_operator.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/style/expression/case.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/style/expression/check_subtype.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/style/expression/coalesce.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/style/expression/coercion.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/style/expression/collator.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/style/expression/collator_expression.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/style/expression/comparison.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/style/expression/compound_expression.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/style/expression/dsl.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/style/expression/error.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/style/expression/expression.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/style/expression/find_zoom_curve.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/style/expression/format_expression.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/style/expression/format_section_override.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/style/expression/formatted.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/style/expression/get_covering_stops.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/style/expression/interpolate.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/style/expression/interpolator.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/style/expression/is_constant.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/style/expression/is_expression.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/style/expression/length.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/style/expression/let.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/style/expression/literal.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/style/expression/match.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/style/expression/parsing_context.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/style/expression/step.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/style/expression/type.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/style/expression/value.hpp
        ${LIB_MBGL_SRC}/mbgl/style/expression/assertion.cpp
        ${LIB_MBGL_SRC}/mbgl/style/expression/at.cpp
        ${LIB_MBGL_SRC}/mbgl/style/expression/boolean_operator.cpp
        ${LIB_MBGL_SRC}/mbgl/style/expression/case.cpp
        ${LIB_MBGL_SRC}/mbgl/style/expression/check_subtype.cpp
        ${LIB_MBGL_SRC}/mbgl/style/expression/coalesce.cpp
        ${LIB_MBGL_SRC}/mbgl/style/expression/coercion.cpp
        ${LIB_MBGL_SRC}/mbgl/style/expression/collator_expression.cpp
        ${LIB_MBGL_SRC}/mbgl/style/expression/comparison.cpp
        ${LIB_MBGL_SRC}/mbgl/style/expression/compound_expression.cpp
        ${LIB_MBGL_SRC}/mbgl/style/expression/dsl.cpp
        ${LIB_MBGL_SRC}/mbgl/style/expression/expression.cpp
        ${LIB_MBGL_SRC}/mbgl/style/expression/find_zoom_curve.cpp
        ${LIB_MBGL_SRC}/mbgl/style/expression/format_expression.cpp
        ${LIB_MBGL_SRC}/mbgl/style/expression/formatted.cpp
        ${LIB_MBGL_SRC}/mbgl/style/expression/get_covering_stops.cpp
        ${LIB_MBGL_SRC}/mbgl/style/expression/interpolate.cpp
        ${LIB_MBGL_SRC}/mbgl/style/expression/is_constant.cpp
        ${LIB_MBGL_SRC}/mbgl/style/expression/is_expression.cpp
        ${LIB_MBGL_SRC}/mbgl/style/expression/length.cpp
        ${LIB_MBGL_SRC}/mbgl/style/expression/let.cpp
        ${LIB_MBGL_SRC}/mbgl/style/expression/literal.cpp
        ${LIB_MBGL_SRC}/mbgl/style/expression/match.cpp
        ${LIB_MBGL_SRC}/mbgl/style/expression/parsing_context.cpp
        ${LIB_MBGL_SRC}/mbgl/style/expression/step.cpp
        ${LIB_MBGL_SRC}/mbgl/style/expression/util.cpp
        ${LIB_MBGL_SRC}/mbgl/style/expression/util.hpp
        ${LIB_MBGL_SRC}/mbgl/style/expression/value.cpp

        # style/layers
        ${LIB_MBGL_INCLUDE}/mbgl/style/layers/background_layer.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/style/layers/circle_layer.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/style/layers/custom_layer.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/style/layers/fill_extrusion_layer.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/style/layers/fill_layer.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/style/layers/heatmap_layer.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/style/layers/hillshade_layer.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/style/layers/line_layer.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/style/layers/raster_layer.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/style/layers/symbol_layer.hpp
        ${LIB_MBGL_SRC}/mbgl/style/layers/background_layer.cpp
        ${LIB_MBGL_SRC}/mbgl/style/layers/background_layer_impl.cpp
        ${LIB_MBGL_SRC}/mbgl/style/layers/background_layer_impl.hpp
        ${LIB_MBGL_SRC}/mbgl/style/layers/background_layer_properties.cpp
        ${LIB_MBGL_SRC}/mbgl/style/layers/background_layer_properties.hpp
        ${LIB_MBGL_SRC}/mbgl/style/layers/circle_layer.cpp
        ${LIB_MBGL_SRC}/mbgl/style/layers/circle_layer_impl.cpp
        ${LIB_MBGL_SRC}/mbgl/style/layers/circle_layer_impl.hpp
        ${LIB_MBGL_SRC}/mbgl/style/layers/circle_layer_properties.cpp
        ${LIB_MBGL_SRC}/mbgl/style/layers/circle_layer_properties.hpp
        ${LIB_MBGL_SRC}/mbgl/style/layers/custom_layer.cpp
        ${LIB_MBGL_SRC}/mbgl/style/layers/custom_layer_impl.cpp
        ${LIB_MBGL_SRC}/mbgl/style/layers/custom_layer_impl.hpp
        ${LIB_MBGL_SRC}/mbgl/style/layers/fill_extrusion_layer.cpp
        ${LIB_MBGL_SRC}/mbgl/style/layers/fill_extrusion_layer_impl.cpp
        ${LIB_MBGL_SRC}/mbgl/style/layers/fill_extrusion_layer_impl.hpp
        ${LIB_MBGL_SRC}/mbgl/style/layers/fill_extrusion_layer_properties.cpp
        ${LIB_MBGL_SRC}/mbgl/style/layers/fill_extrusion_layer_properties.hpp
        ${LIB_MBGL_SRC}/mbgl/style/layers/fill_layer.cpp
        ${LIB_MBGL_SRC}/mbgl/style/layers/fill_layer_impl.cpp
        ${LIB_MBGL_SRC}/mbgl/style/layers/fill_layer_impl.hpp
        ${LIB_MBGL_SRC}/mbgl/style/layers/fill_layer_properties.cpp
        ${LIB_MBGL_SRC}/mbgl/style/layers/fill_layer_properties.hpp
        ${LIB_MBGL_SRC}/mbgl/style/layers/heatmap_layer.cpp
        ${LIB_MBGL_SRC}/mbgl/style/layers/heatmap_layer_impl.cpp
        ${LIB_MBGL_SRC}/mbgl/style/layers/heatmap_layer_impl.hpp
        ${LIB_MBGL_SRC}/mbgl/style/layers/heatmap_layer_properties.cpp
        ${LIB_MBGL_SRC}/mbgl/style/layers/heatmap_layer_properties.hpp
        ${LIB_MBGL_SRC}/mbgl/style/layers/hillshade_layer.cpp
        ${LIB_MBGL_SRC}/mbgl/style/layers/hillshade_layer_impl.cpp
        ${LIB_MBGL_SRC}/mbgl/style/layers/hillshade_layer_impl.hpp
        ${LIB_MBGL_SRC}/mbgl/style/layers/hillshade_layer_properties.cpp
        ${LIB_MBGL_SRC}/mbgl/style/layers/hillshade_layer_properties.hpp
        ${LIB_MBGL_SRC}/mbgl/style/layers/line_layer.cpp
        ${LIB_MBGL_SRC}/mbgl/style/layers/line_layer_impl.cpp
        ${LIB_MBGL_SRC}/mbgl/style/layers/line_layer_impl.hpp
        ${LIB_MBGL_SRC}/mbgl/style/layers/line_layer_properties.cpp
        ${LIB_MBGL_SRC}/mbgl/style/layers/line_layer_properties.hpp
        ${LIB_MBGL_SRC}/mbgl/style/layers/raster_layer.cpp
        ${LIB_MBGL_SRC}/mbgl/style/layers/raster_layer_impl.cpp
        ${LIB_MBGL_SRC}/mbgl/style/layers/raster_layer_impl.hpp
        ${LIB_MBGL_SRC}/mbgl/style/layers/raster_layer_properties.cpp
        ${LIB_MBGL_SRC}/mbgl/style/layers/raster_layer_properties.hpp
        ${LIB_MBGL_SRC}/mbgl/style/layers/symbol_layer.cpp
        ${LIB_MBGL_SRC}/mbgl/style/layers/symbol_layer_impl.cpp
        ${LIB_MBGL_SRC}/mbgl/style/layers/symbol_layer_impl.hpp
        ${LIB_MBGL_SRC}/mbgl/style/layers/symbol_layer_properties.cpp
        ${LIB_MBGL_SRC}/mbgl/style/layers/symbol_layer_properties.hpp

        # style/sources
        ${LIB_MBGL_INCLUDE}/mbgl/style/sources/custom_geometry_source.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/style/sources/geojson_source.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/style/sources/image_source.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/style/sources/raster_dem_source.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/style/sources/raster_source.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/style/sources/vector_source.hpp
        ${LIB_MBGL_SRC}/mbgl/style/sources/custom_geometry_source.cpp
        ${LIB_MBGL_SRC}/mbgl/style/sources/custom_geometry_source_impl.cpp
        ${LIB_MBGL_SRC}/mbgl/style/sources/custom_geometry_source_impl.hpp
        ${LIB_MBGL_SRC}/mbgl/style/sources/geojson_source.cpp
        ${LIB_MBGL_SRC}/mbgl/style/sources/geojson_source_impl.cpp
        ${LIB_MBGL_SRC}/mbgl/style/sources/geojson_source_impl.hpp
        ${LIB_MBGL_SRC}/mbgl/style/sources/image_source.cpp
        ${LIB_MBGL_SRC}/mbgl/style/sources/image_source_impl.cpp
        ${LIB_MBGL_SRC}/mbgl/style/sources/image_source_impl.hpp
        ${LIB_MBGL_SRC}/mbgl/style/sources/raster_dem_source.cpp
        ${LIB_MBGL_SRC}/mbgl/style/sources/raster_source.cpp
        ${LIB_MBGL_SRC}/mbgl/style/sources/raster_source_impl.cpp
        ${LIB_MBGL_SRC}/mbgl/style/sources/raster_source_impl.hpp
        ${LIB_MBGL_SRC}/mbgl/style/sources/vector_source.cpp
        ${LIB_MBGL_SRC}/mbgl/style/sources/vector_source_impl.cpp
        ${LIB_MBGL_SRC}/mbgl/style/sources/vector_source_impl.hpp

        # text
        ${LIB_MBGL_SRC}/mbgl/text/bidi.hpp
        ${LIB_MBGL_SRC}/mbgl/text/check_max_angle.cpp
        ${LIB_MBGL_SRC}/mbgl/text/check_max_angle.hpp
        ${LIB_MBGL_SRC}/mbgl/text/collision_feature.cpp
        ${LIB_MBGL_SRC}/mbgl/text/collision_feature.hpp
        ${LIB_MBGL_SRC}/mbgl/text/collision_index.cpp
        ${LIB_MBGL_SRC}/mbgl/text/collision_index.hpp
        ${LIB_MBGL_SRC}/mbgl/text/cross_tile_symbol_index.cpp
        ${LIB_MBGL_SRC}/mbgl/text/cross_tile_symbol_index.hpp
        ${LIB_MBGL_SRC}/mbgl/text/get_anchors.cpp
        ${LIB_MBGL_SRC}/mbgl/text/get_anchors.hpp
        ${LIB_MBGL_SRC}/mbgl/text/glyph.cpp
        ${LIB_MBGL_SRC}/mbgl/text/glyph.hpp
        ${LIB_MBGL_SRC}/mbgl/text/glyph_atlas.cpp
        ${LIB_MBGL_SRC}/mbgl/text/glyph_atlas.hpp
        ${LIB_MBGL_SRC}/mbgl/text/glyph_manager.cpp
        ${LIB_MBGL_SRC}/mbgl/text/glyph_manager.hpp
        ${LIB_MBGL_SRC}/mbgl/text/glyph_manager_observer.hpp
        ${LIB_MBGL_SRC}/mbgl/text/glyph_pbf.cpp
        ${LIB_MBGL_SRC}/mbgl/text/glyph_pbf.hpp
        ${LIB_MBGL_SRC}/mbgl/text/glyph_range.hpp
        ${LIB_MBGL_SRC}/mbgl/text/language_tag.cpp
        ${LIB_MBGL_SRC}/mbgl/text/language_tag.hpp
        ${LIB_MBGL_SRC}/mbgl/text/local_glyph_rasterizer.hpp
        ${LIB_MBGL_SRC}/mbgl/text/placement.cpp
        ${LIB_MBGL_SRC}/mbgl/text/placement.hpp
        ${LIB_MBGL_SRC}/mbgl/text/quads.cpp
        ${LIB_MBGL_SRC}/mbgl/text/quads.hpp
        ${LIB_MBGL_SRC}/mbgl/text/shaping.cpp
        ${LIB_MBGL_SRC}/mbgl/text/shaping.hpp
        ${LIB_MBGL_SRC}/mbgl/text/tagged_string.cpp
        ${LIB_MBGL_SRC}/mbgl/text/tagged_string.hpp

        # tile
        ${LIB_MBGL_INCLUDE}/mbgl/tile/tile_id.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/tile/tile_necessity.hpp
        ${LIB_MBGL_SRC}/mbgl/tile/custom_geometry_tile.cpp
        ${LIB_MBGL_SRC}/mbgl/tile/custom_geometry_tile.hpp
        ${LIB_MBGL_SRC}/mbgl/tile/geojson_tile.cpp
        ${LIB_MBGL_SRC}/mbgl/tile/geojson_tile.hpp
        ${LIB_MBGL_SRC}/mbgl/tile/geojson_tile_data.hpp
        ${LIB_MBGL_SRC}/mbgl/tile/geometry_tile.cpp
        ${LIB_MBGL_SRC}/mbgl/tile/geometry_tile.hpp
        ${LIB_MBGL_SRC}/mbgl/tile/geometry_tile_data.cpp
        ${LIB_MBGL_SRC}/mbgl/tile/geometry_tile_data.hpp
        ${LIB_MBGL_SRC}/mbgl/tile/geometry_tile_worker.cpp
        ${LIB_MBGL_SRC}/mbgl/tile/geometry_tile_worker.hpp
        ${LIB_MBGL_SRC}/mbgl/tile/raster_dem_tile.cpp
        ${LIB_MBGL_SRC}/mbgl/tile/raster_dem_tile.hpp
        ${LIB_MBGL_SRC}/mbgl/tile/raster_dem_tile_worker.cpp
        ${LIB_MBGL_SRC}/mbgl/tile/raster_dem_tile_worker.hpp
        ${LIB_MBGL_SRC}/mbgl/tile/raster_tile.cpp
        ${LIB_MBGL_SRC}/mbgl/tile/raster_tile.hpp
        ${LIB_MBGL_SRC}/mbgl/tile/raster_tile_worker.cpp
        ${LIB_MBGL_SRC}/mbgl/tile/raster_tile_worker.hpp
        ${LIB_MBGL_SRC}/mbgl/tile/tile.cpp
        ${LIB_MBGL_SRC}/mbgl/tile/tile.hpp
        ${LIB_MBGL_SRC}/mbgl/tile/tile_cache.cpp
        ${LIB_MBGL_SRC}/mbgl/tile/tile_cache.hpp
        ${LIB_MBGL_SRC}/mbgl/tile/tile_id_hash.cpp
        ${LIB_MBGL_SRC}/mbgl/tile/tile_id_io.cpp
        ${LIB_MBGL_SRC}/mbgl/tile/tile_loader.hpp
        ${LIB_MBGL_SRC}/mbgl/tile/tile_loader_impl.hpp
        ${LIB_MBGL_SRC}/mbgl/tile/tile_observer.hpp
        ${LIB_MBGL_SRC}/mbgl/tile/vector_tile.cpp
        ${LIB_MBGL_SRC}/mbgl/tile/vector_tile.hpp
        ${LIB_MBGL_SRC}/mbgl/tile/vector_tile_data.cpp
        ${LIB_MBGL_SRC}/mbgl/tile/vector_tile_data.hpp

        # util
        ${LIB_MBGL_INCLUDE}/mbgl/util/async_request.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/util/async_task.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/util/char_array_buffer.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/util/chrono.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/util/color.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/util/compression.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/util/constants.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/util/convert.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/util/enum.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/util/event.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/util/exception.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/util/expected.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/util/feature.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/util/font_stack.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/util/geo.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/util/geojson.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/util/geometry.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/util/ignore.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/util/image.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/util/immutable.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/util/indexed_tuple.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/util/interpolate.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/util/logging.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/util/noncopyable.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/util/optional.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/util/peer.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/util/platform.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/util/premultiply.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/util/projection.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/util/range.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/util/run_loop.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/util/size.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/util/string.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/util/thread.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/util/tileset.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/util/timer.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/util/traits.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/util/type_list.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/util/unitbezier.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/util/util.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/util/variant.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/util/work_request.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/util/work_task.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/util/work_task_impl.hpp
        ${LIB_MBGL_SRC}/mbgl/util/chrono.cpp
        ${LIB_MBGL_SRC}/mbgl/util/clip_id.cpp
        ${LIB_MBGL_SRC}/mbgl/util/clip_id.hpp
        ${LIB_MBGL_SRC}/mbgl/util/color.cpp
        ${LIB_MBGL_SRC}/mbgl/util/compression.cpp
        ${LIB_MBGL_SRC}/mbgl/util/constants.cpp
        ${LIB_MBGL_SRC}/mbgl/util/convert.cpp
        ${LIB_MBGL_SRC}/mbgl/util/dtoa.cpp
        ${LIB_MBGL_SRC}/mbgl/util/dtoa.hpp
        ${LIB_MBGL_SRC}/mbgl/util/event.cpp
        ${LIB_MBGL_SRC}/mbgl/util/font_stack.cpp
        ${LIB_MBGL_SRC}/mbgl/util/geo.cpp
        ${LIB_MBGL_SRC}/mbgl/util/geojson_impl.cpp
        ${LIB_MBGL_SRC}/mbgl/util/grid_index.cpp
        ${LIB_MBGL_SRC}/mbgl/util/grid_index.hpp
        ${LIB_MBGL_SRC}/mbgl/util/hash.hpp
        ${LIB_MBGL_SRC}/mbgl/util/http_header.cpp
        ${LIB_MBGL_SRC}/mbgl/util/http_header.hpp
        ${LIB_MBGL_SRC}/mbgl/util/http_timeout.cpp
        ${LIB_MBGL_SRC}/mbgl/util/http_timeout.hpp
        ${LIB_MBGL_SRC}/mbgl/util/i18n.cpp
        ${LIB_MBGL_SRC}/mbgl/util/i18n.hpp
        ${LIB_MBGL_SRC}/mbgl/util/interpolate.cpp
        ${LIB_MBGL_SRC}/mbgl/util/intersection_tests.cpp
        ${LIB_MBGL_SRC}/mbgl/util/intersection_tests.hpp
        ${LIB_MBGL_SRC}/mbgl/util/io.cpp
        ${LIB_MBGL_SRC}/mbgl/util/io.hpp
        ${LIB_MBGL_SRC}/mbgl/util/literal.hpp
        ${LIB_MBGL_SRC}/mbgl/util/logging.cpp
        ${LIB_MBGL_SRC}/mbgl/util/longest_common_subsequence.hpp
        ${LIB_MBGL_SRC}/mbgl/util/mapbox.cpp
        ${LIB_MBGL_SRC}/mbgl/util/mapbox.hpp
        ${LIB_MBGL_SRC}/mbgl/util/mat2.cpp
        ${LIB_MBGL_SRC}/mbgl/util/mat2.hpp
        ${LIB_MBGL_SRC}/mbgl/util/mat3.cpp
        ${LIB_MBGL_SRC}/mbgl/util/mat3.hpp
        ${LIB_MBGL_SRC}/mbgl/util/mat4.cpp
        ${LIB_MBGL_SRC}/mbgl/util/mat4.hpp
        ${LIB_MBGL_SRC}/mbgl/util/math.hpp
        ${LIB_MBGL_SRC}/mbgl/util/premultiply.cpp
        ${LIB_MBGL_SRC}/mbgl/util/rapidjson.cpp
        ${LIB_MBGL_SRC}/mbgl/util/rapidjson.hpp
        ${LIB_MBGL_SRC}/mbgl/util/rect.hpp
        ${LIB_MBGL_SRC}/mbgl/util/std.hpp
        ${LIB_MBGL_SRC}/mbgl/util/stopwatch.cpp
        ${LIB_MBGL_SRC}/mbgl/util/stopwatch.hpp
        ${LIB_MBGL_SRC}/mbgl/util/string.cpp
        ${LIB_MBGL_SRC}/mbgl/util/thread_local.hpp
        ${LIB_MBGL_SRC}/mbgl/util/tile_coordinate.hpp
        ${LIB_MBGL_SRC}/mbgl/util/tile_cover.cpp
        ${LIB_MBGL_SRC}/mbgl/util/tile_cover.hpp
        ${LIB_MBGL_SRC}/mbgl/util/tile_cover_impl.cpp
        ${LIB_MBGL_SRC}/mbgl/util/tile_cover_impl.hpp
        ${LIB_MBGL_SRC}/mbgl/util/tile_range.hpp
        ${LIB_MBGL_SRC}/mbgl/util/tiny_sdf.cpp
        ${LIB_MBGL_SRC}/mbgl/util/tiny_sdf.hpp
        ${LIB_MBGL_SRC}/mbgl/util/token.hpp
        ${LIB_MBGL_SRC}/mbgl/util/url.cpp
        ${LIB_MBGL_SRC}/mbgl/util/url.hpp
        ${LIB_MBGL_SRC}/mbgl/util/utf.hpp
        ${LIB_MBGL_SRC}/mbgl/util/version.cpp
        ${LIB_MBGL_SRC}/mbgl/util/version.hpp
        ${LIB_MBGL_SRC}/mbgl/util/work_request.cpp


        ##################################### platform/default/filesource.cmake - filesource-files.json ############################
        # sources
        ${LIB_MBGL_PLATFORM}/default/asset_file_source.cpp
        ${LIB_MBGL_PLATFORM}/default/default_file_source.cpp
        ${LIB_MBGL_PLATFORM}/default/file_source_request.cpp
        ${LIB_MBGL_PLATFORM}/default/local_file_request.cpp
        ${LIB_MBGL_PLATFORM}/default/local_file_source.cpp
        ${LIB_MBGL_PLATFORM}/default/mbgl/storage/offline.cpp
        ${LIB_MBGL_PLATFORM}/default/mbgl/storage/offline_database.cpp
        ${LIB_MBGL_PLATFORM}/default/mbgl/storage/offline_download.cpp
        ${LIB_MBGL_PLATFORM}/default/online_file_source.cpp

        # public_headers
        ${LIB_MBGL_INCLUDE}/mbgl/storage/default_file_source.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/storage/offline.hpp
        ${LIB_MBGL_INCLUDE}/mbgl/storage/online_file_source.hpp
        ${LIB_MBGL_PLATFORM}/default/mbgl/storage/file_source_request.hpp
        ${LIB_MBGL_PLATFORM}/default/mbgl/storage/local_file_request.hpp
        ${LIB_MBGL_PLATFORM}/default/mbgl/storage/merge_sideloaded.hpp
        ${LIB_MBGL_PLATFORM}/default/mbgl/storage/offline_database.hpp
        ${LIB_MBGL_PLATFORM}/default/mbgl/storage/offline_download.hpp
        ${LIB_MBGL_PLATFORM}/default/mbgl/storage/offline_schema.hpp
        ${LIB_MBGL_PLATFORM}/default/mbgl/storage/sqlite3.hpp

        # private_headers
        ${LIB_MBGL_SRC}/mbgl/storage/asset_file_source.hpp
        ${LIB_MBGL_SRC}/mbgl/storage/http_file_source.hpp
        ${LIB_MBGL_SRC}/mbgl/storage/local_file_source.hpp


        ############################################################### /platform/android/config.cmake - core-files.json##
        # sources
        ${LIB_MBGL_PLATFORM}/android/src/main.cpp
        ${LIB_MBGL_PLATFORM}/android/src/android_renderer_backend.cpp
        ${LIB_MBGL_PLATFORM}/android/src/android_renderer_frontend.cpp
        ${LIB_MBGL_PLATFORM}/android/src/annotation/marker.cpp
        ${LIB_MBGL_PLATFORM}/android/src/annotation/polygon.cpp
        ${LIB_MBGL_PLATFORM}/android/src/annotation/polyline.cpp
        ${LIB_MBGL_PLATFORM}/android/src/async_task.cpp
        ${LIB_MBGL_PLATFORM}/android/src/attach_env.cpp
        ${LIB_MBGL_PLATFORM}/android/src/bitmap.cpp
        ${LIB_MBGL_PLATFORM}/android/src/bitmap_factory.cpp
        ${LIB_MBGL_PLATFORM}/android/src/conversion/collection.cpp
        ${LIB_MBGL_PLATFORM}/android/src/conversion/color.cpp
        ${LIB_MBGL_PLATFORM}/android/src/conversion/constant.cpp
        ${LIB_MBGL_PLATFORM}/android/src/geojson/feature.cpp
        ${LIB_MBGL_PLATFORM}/android/src/geojson/feature_collection.cpp
        ${LIB_MBGL_PLATFORM}/android/src/geojson/geometry.cpp
        ${LIB_MBGL_PLATFORM}/android/src/geojson/geometry_collection.cpp
        ${LIB_MBGL_PLATFORM}/android/src/geojson/line_string.cpp
        ${LIB_MBGL_PLATFORM}/android/src/geojson/multi_line_string.cpp
        ${LIB_MBGL_PLATFORM}/android/src/geojson/multi_point.cpp
        ${LIB_MBGL_PLATFORM}/android/src/geojson/multi_polygon.cpp
        ${LIB_MBGL_PLATFORM}/android/src/geojson/point.cpp
        ${LIB_MBGL_PLATFORM}/android/src/geojson/polygon.cpp
        ${LIB_MBGL_PLATFORM}/android/src/geometry/lat_lng.cpp
        ${LIB_MBGL_PLATFORM}/android/src/geometry/lat_lng_bounds.cpp
        ${LIB_MBGL_PLATFORM}/android/src/geometry/lat_lng_quad.cpp
        ${LIB_MBGL_PLATFORM}/android/src/geometry/projected_meters.cpp
        ${LIB_MBGL_PLATFORM}/android/src/graphics/pointf.cpp
        ${LIB_MBGL_PLATFORM}/android/src/graphics/rectf.cpp
        ${LIB_MBGL_PLATFORM}/android/src/gson/json_array.cpp
        ${LIB_MBGL_PLATFORM}/android/src/gson/json_element.cpp
        ${LIB_MBGL_PLATFORM}/android/src/gson/json_object.cpp
        ${LIB_MBGL_PLATFORM}/android/src/gson/json_primitive.cpp
        ${LIB_MBGL_PLATFORM}/android/src/image.cpp
        ${LIB_MBGL_PLATFORM}/android/src/java/util.cpp
        ${LIB_MBGL_PLATFORM}/android/src/java_types.cpp
        ${LIB_MBGL_PLATFORM}/android/src/jni.cpp
        ${LIB_MBGL_PLATFORM}/android/src/logger.cpp
        ${LIB_MBGL_PLATFORM}/android/src/logging_android.cpp
        ${LIB_MBGL_PLATFORM}/android/src/map/camera_position.cpp
        ${LIB_MBGL_PLATFORM}/android/src/map/image.cpp
        ${LIB_MBGL_PLATFORM}/android/src/map_renderer.cpp
        ${LIB_MBGL_PLATFORM}/android/src/map_renderer_runnable.cpp
        ${LIB_MBGL_PLATFORM}/android/src/native_map_view.cpp
        ${LIB_MBGL_PLATFORM}/android/src/run_loop.cpp
        ${LIB_MBGL_PLATFORM}/android/src/snapshotter/map_snapshot.cpp
        ${LIB_MBGL_PLATFORM}/android/src/snapshotter/map_snapshotter.cpp
        ${LIB_MBGL_PLATFORM}/android/src/string_util.cpp
        ${LIB_MBGL_PLATFORM}/android/src/style/conversion/filter.cpp
        ${LIB_MBGL_PLATFORM}/android/src/style/conversion/position.cpp
        ${LIB_MBGL_PLATFORM}/android/src/style/conversion/transition_options.cpp
        ${LIB_MBGL_PLATFORM}/android/src/style/conversion/url_or_tileset.cpp
        ${LIB_MBGL_PLATFORM}/android/src/style/formatted.cpp
        ${LIB_MBGL_PLATFORM}/android/src/style/formatted_section.cpp
        ${LIB_MBGL_PLATFORM}/android/src/style/layers/background_layer.cpp
        ${LIB_MBGL_PLATFORM}/android/src/style/layers/circle_layer.cpp
        ${LIB_MBGL_PLATFORM}/android/src/style/layers/custom_layer.cpp
        ${LIB_MBGL_PLATFORM}/android/src/style/layers/fill_extrusion_layer.cpp
        ${LIB_MBGL_PLATFORM}/android/src/style/layers/fill_layer.cpp
        ${LIB_MBGL_PLATFORM}/android/src/style/layers/heatmap_layer.cpp
        ${LIB_MBGL_PLATFORM}/android/src/style/layers/hillshade_layer.cpp
        ${LIB_MBGL_PLATFORM}/android/src/style/layers/layer.cpp
        ${LIB_MBGL_PLATFORM}/android/src/style/layers/layer_manager.cpp
        ${LIB_MBGL_PLATFORM}/android/src/style/layers/line_layer.cpp
        ${LIB_MBGL_PLATFORM}/android/src/style/layers/raster_layer.cpp
        ${LIB_MBGL_PLATFORM}/android/src/style/layers/symbol_layer.cpp
        ${LIB_MBGL_PLATFORM}/android/src/style/light.cpp
        ${LIB_MBGL_PLATFORM}/android/src/style/position.cpp
        ${LIB_MBGL_PLATFORM}/android/src/style/sources/custom_geometry_source.cpp
        ${LIB_MBGL_PLATFORM}/android/src/style/sources/geojson_source.cpp
        ${LIB_MBGL_PLATFORM}/android/src/style/sources/image_source.cpp
        ${LIB_MBGL_PLATFORM}/android/src/style/sources/raster_dem_source.cpp
        ${LIB_MBGL_PLATFORM}/android/src/style/sources/raster_source.cpp
        ${LIB_MBGL_PLATFORM}/android/src/style/sources/source.cpp
        ${LIB_MBGL_PLATFORM}/android/src/style/sources/unknown_source.cpp
        ${LIB_MBGL_PLATFORM}/android/src/style/sources/vector_source.cpp
        ${LIB_MBGL_PLATFORM}/android/src/style/transition_options.cpp
        ${LIB_MBGL_PLATFORM}/android/src/style/value.cpp
        ${LIB_MBGL_PLATFORM}/android/src/text/collator.cpp
        ${LIB_MBGL_PLATFORM}/android/src/text/local_glyph_rasterizer.cpp
        ${LIB_MBGL_PLATFORM}/android/src/gl_functions.cpp
        ${LIB_MBGL_PLATFORM}/android/src/thread.cpp
        ${LIB_MBGL_PLATFORM}/android/src/timer.cpp
        ${LIB_MBGL_PLATFORM}/android/src/unaccent.cpp
        ${LIB_MBGL_PLATFORM}/default/mbgl/gl/headless_backend.cpp
        ${LIB_MBGL_PLATFORM}/default/mbgl/gl/headless_frontend.cpp
        ${LIB_MBGL_PLATFORM}/default/mbgl/map/map_snapshotter.cpp
        ${LIB_MBGL_PLATFORM}/default/bidi.cpp
        ${LIB_MBGL_PLATFORM}/default/mbgl/util/default_thread_pool.cpp
        ${LIB_MBGL_PLATFORM}/default/png_writer.cpp
        ${LIB_MBGL_PLATFORM}/default/mbgl/util/shared_thread_pool.cpp
        ${LIB_MBGL_PLATFORM}/default/thread_local.cpp
        ${LIB_MBGL_PLATFORM}/default/utf.cpp
        ${LIB_MBGL_PLATFORM}/linux/src/headless_backend_egl.cpp

        # public_headers
        ${LIB_MBGL_PLATFORM}/default/jni/string_conversion.hpp
        ${LIB_MBGL_PLATFORM}/default/mbgl/gl/headless_backend.hpp
        ${LIB_MBGL_PLATFORM}/default/mbgl/gl/headless_frontend.hpp
        ${LIB_MBGL_PLATFORM}/default/mbgl/map/map_snapshotter.hpp
        ${LIB_MBGL_PLATFORM}/default/mbgl/text/unaccent.hpp
        ${LIB_MBGL_PLATFORM}/default/mbgl/util/default_thread_pool.hpp
        ${LIB_MBGL_PLATFORM}/default/mbgl/util/shared_thread_pool.hpp

        # private_headers
        ${LIB_MBGL_PLATFORM}/android/src/annotation/marker.hpp
        ${LIB_MBGL_PLATFORM}/android/src/annotation/multi_point.hpp
        ${LIB_MBGL_PLATFORM}/android/src/annotation/polygon.hpp
        ${LIB_MBGL_PLATFORM}/android/src/annotation/polyline.hpp
        ${LIB_MBGL_PLATFORM}/android/src/attach_env.hpp
        ${LIB_MBGL_PLATFORM}/android/src/bitmap.hpp
        ${LIB_MBGL_PLATFORM}/android/src/bitmap_factory.hpp
        ${LIB_MBGL_PLATFORM}/android/src/conversion/collection.hpp
        ${LIB_MBGL_PLATFORM}/android/src/conversion/color.hpp
        ${LIB_MBGL_PLATFORM}/android/src/conversion/constant.hpp
        ${LIB_MBGL_PLATFORM}/android/src/conversion/conversion.hpp
        ${LIB_MBGL_PLATFORM}/android/src/geojson/feature.hpp
        ${LIB_MBGL_PLATFORM}/android/src/geojson/feature_collection.hpp
        ${LIB_MBGL_PLATFORM}/android/src/geojson/geometry.hpp
        ${LIB_MBGL_PLATFORM}/android/src/geojson/geometry_collection.hpp
        ${LIB_MBGL_PLATFORM}/android/src/geojson/line_string.hpp
        ${LIB_MBGL_PLATFORM}/android/src/geojson/multi_line_string.hpp
        ${LIB_MBGL_PLATFORM}/android/src/geojson/multi_point.hpp
        ${LIB_MBGL_PLATFORM}/android/src/geojson/multi_polygon.hpp
        ${LIB_MBGL_PLATFORM}/android/src/geojson/point.hpp
        ${LIB_MBGL_PLATFORM}/android/src/geojson/polygon.hpp
        ${LIB_MBGL_PLATFORM}/android/src/geojson/util.hpp
        ${LIB_MBGL_PLATFORM}/android/src/geometry/lat_lng.hpp
        ${LIB_MBGL_PLATFORM}/android/src/geometry/lat_lng_bounds.hpp
        ${LIB_MBGL_PLATFORM}/android/src/geometry/lat_lng_quad.hpp
        ${LIB_MBGL_PLATFORM}/android/src/geometry/projected_meters.hpp
        ${LIB_MBGL_PLATFORM}/android/src/graphics/pointf.hpp
        ${LIB_MBGL_PLATFORM}/android/src/graphics/rectf.hpp
        ${LIB_MBGL_PLATFORM}/android/src/gson/json_array.hpp
        ${LIB_MBGL_PLATFORM}/android/src/gson/json_element.hpp
        ${LIB_MBGL_PLATFORM}/android/src/gson/json_object.hpp
        ${LIB_MBGL_PLATFORM}/android/src/gson/json_primitive.hpp
        ${LIB_MBGL_PLATFORM}/android/src/java/util.hpp
        ${LIB_MBGL_PLATFORM}/android/src/java_types.hpp
        ${LIB_MBGL_PLATFORM}/android/src/jni.hpp
        ${LIB_MBGL_PLATFORM}/android/src/logger.hpp
        ${LIB_MBGL_PLATFORM}/android/src/http_file_source.cpp
        ${LIB_MBGL_PLATFORM}/android/src/map/camera_position.hpp
        ${LIB_MBGL_PLATFORM}/android/src/map/image.hpp
        ${LIB_MBGL_PLATFORM}/android/src/map_renderer.hpp
        ${LIB_MBGL_PLATFORM}/android/src/map_renderer_runnable.hpp
        ${LIB_MBGL_PLATFORM}/android/src/native_map_view.hpp
        ${LIB_MBGL_PLATFORM}/android/src/run_loop_impl.hpp
        ${LIB_MBGL_PLATFORM}/android/src/snapshotter/map_snapshot.hpp
        ${LIB_MBGL_PLATFORM}/android/src/snapshotter/map_snapshotter.hpp
        ${LIB_MBGL_PLATFORM}/android/src/style/android_conversion.hpp
        ${LIB_MBGL_PLATFORM}/android/src/style/conversion/filter.hpp
        ${LIB_MBGL_PLATFORM}/android/src/style/conversion/position.hpp
        ${LIB_MBGL_PLATFORM}/android/src/style/conversion/property_expression.hpp
        ${LIB_MBGL_PLATFORM}/android/src/style/conversion/property_value.hpp
        ${LIB_MBGL_PLATFORM}/android/src/style/conversion/transition_options.hpp
        ${LIB_MBGL_PLATFORM}/android/src/style/conversion/url_or_tileset.hpp
        ${LIB_MBGL_PLATFORM}/android/src/style/formatted.hpp
        ${LIB_MBGL_PLATFORM}/android/src/style/formatted_section.hpp
        ${LIB_MBGL_PLATFORM}/android/src/style/layers/background_layer.hpp
        ${LIB_MBGL_PLATFORM}/android/src/style/layers/circle_layer.hpp
        ${LIB_MBGL_PLATFORM}/android/src/style/layers/custom_layer.hpp
        ${LIB_MBGL_PLATFORM}/android/src/style/layers/fill_extrusion_layer.hpp
        ${LIB_MBGL_PLATFORM}/android/src/style/layers/fill_layer.hpp
        ${LIB_MBGL_PLATFORM}/android/src/style/layers/heatmap_layer.hpp
        ${LIB_MBGL_PLATFORM}/android/src/style/layers/hillshade_layer.hpp
        ${LIB_MBGL_PLATFORM}/android/src/style/layers/layer.hpp
        ${LIB_MBGL_PLATFORM}/android/src/style/layers/layer_manager.hpp
        ${LIB_MBGL_PLATFORM}/android/src/style/layers/line_layer.hpp
        ${LIB_MBGL_PLATFORM}/android/src/style/layers/raster_layer.hpp
        ${LIB_MBGL_PLATFORM}/android/src/style/layers/symbol_layer.hpp
        ${LIB_MBGL_PLATFORM}/android/src/style/light.hpp
        ${LIB_MBGL_PLATFORM}/android/src/style/position.hpp
        ${LIB_MBGL_PLATFORM}/android/src/style/sources/custom_geometry_source.hpp
        ${LIB_MBGL_PLATFORM}/android/src/style/sources/geojson_source.hpp
        ${LIB_MBGL_PLATFORM}/android/src/style/sources/image_source.hpp
        ${LIB_MBGL_PLATFORM}/android/src/style/sources/raster_dem_source.hpp
        ${LIB_MBGL_PLATFORM}/android/src/style/sources/raster_source.hpp
        ${LIB_MBGL_PLATFORM}/android/src/style/sources/source.hpp
        ${LIB_MBGL_PLATFORM}/android/src/style/sources/unknown_source.hpp
        ${LIB_MBGL_PLATFORM}/android/src/style/sources/vector_source.hpp
        ${LIB_MBGL_PLATFORM}/android/src/style/transition_options.hpp
        ${LIB_MBGL_PLATFORM}/android/src/style/value.hpp
        ${LIB_MBGL_PLATFORM}/android/src/text/collator_jni.hpp
        ${LIB_MBGL_PLATFORM}/android/src/text/local_glyph_rasterizer_jni.hpp



        ############################################################### 누락? ##
        ${LIB_MBGL_PLATFORM}/android/src/asset_manager.hpp
        ${LIB_MBGL_PLATFORM}/android/src/asset_manager_file_source.cpp
        ${LIB_MBGL_PLATFORM}/android/src/asset_manager_file_source.hpp
        ${LIB_MBGL_PLATFORM}/android/src/connectivity_listener.cpp
        ${LIB_MBGL_PLATFORM}/android/src/connectivity_listener.hpp
        ${LIB_MBGL_PLATFORM}/android/src/file_source.cpp
        ${LIB_MBGL_PLATFORM}/android/src/file_source.hpp
        ${LIB_MBGL_PLATFORM}/android/src/offline/offline_manager.cpp
        ${LIB_MBGL_PLATFORM}/android/src/offline/offline_manager.hpp
        ${LIB_MBGL_PLATFORM}/android/src/offline/offline_region.cpp
        ${LIB_MBGL_PLATFORM}/android/src/offline/offline_region.hpp
        ${LIB_MBGL_PLATFORM}/android/src/offline/offline_region_definition.cpp
        ${LIB_MBGL_PLATFORM}/android/src/offline/offline_region_definition.hpp
        ${LIB_MBGL_PLATFORM}/android/src/offline/offline_region_error.cpp
        ${LIB_MBGL_PLATFORM}/android/src/offline/offline_region_error.hpp
        ${LIB_MBGL_PLATFORM}/android/src/offline/offline_region_status.cpp
        ${LIB_MBGL_PLATFORM}/android/src/offline/offline_region_status.hpp
        ${LIB_MBGL_PLATFORM}/default/sqlite3.cpp

        ${LIB_MBGL_PLATFORM}/android/src/gl_functions.cpp

        ############################################################### lib_sqlite ##
        ${IMPORT_PKG_DIR}/sqlite/src/sqlite3.c
        ${IMPORT_PKG_DIR}/sqlite/include/sqlite3.h


        ############################################################### lib_icu ##
        ${CMAKE_SOURCE_DIR}/vendor/icu/src/cmemory.cpp
        ${CMAKE_SOURCE_DIR}/vendor/icu/src/cstring.cpp
        ${CMAKE_SOURCE_DIR}/vendor/icu/src/ubidi.cpp
        ${CMAKE_SOURCE_DIR}/vendor/icu/src/ubidi_props.cpp
        ${CMAKE_SOURCE_DIR}/vendor/icu/src/ubidiln.cpp
        ${CMAKE_SOURCE_DIR}/vendor/icu/src/ubidiwrt.cpp
        ${CMAKE_SOURCE_DIR}/vendor/icu/src/uchar.cpp
        ${CMAKE_SOURCE_DIR}/vendor/icu/src/udataswp.cpp
        ${CMAKE_SOURCE_DIR}/vendor/icu/src/uinvchar.cpp
        ${CMAKE_SOURCE_DIR}/vendor/icu/src/umath.cpp
        ${CMAKE_SOURCE_DIR}/vendor/icu/src/ushape.cpp
        ${CMAKE_SOURCE_DIR}/vendor/icu/src/ustring.cpp
        ${CMAKE_SOURCE_DIR}/vendor/icu/src/utf_impl.cpp
        ${CMAKE_SOURCE_DIR}/vendor/icu/src/utrie2.cpp
        ${CMAKE_SOURCE_DIR}/vendor/icu/src/utypes.cpp

        )